"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { 
  BookOpen,
  Download,
  Settings,
  Code,
  Zap,
  Mic,
  Palette,
  Command,
  Database,
  Shield,
  Layers,
  CheckCircle,
  AlertCircle,
  ExternalLink,
  ChevronRight,
  Terminal,
  Globe,
  Cpu,
  Users
} from "lucide-react"
import Link from "next/link"
import { SDKNav } from "@/components/sdk-nav"
import { PrismCode } from "@/components/prism-code"
import { DocsContent } from "@/components/docs-content"

// Import generated documentation if available
let generatedDocs: any = {};
let docSections: any[] = [];

try {
  // These will be generated by the build script
  const docsModule = require('./content/index');
  generatedDocs = docsModule.allDocs || {};
  const sectionsModule = require('./content/sections');
  docSections = sectionsModule.docSections || [];
} catch (e) {
  // Documentation not built yet
  console.log('Documentation not built yet. Run pnpm build:docs');
}

// Merge generated sections with nav sections
const navSections = [
  {
    title: "Getting Started",
    items: [
      { id: "overview", title: "Overview" },
      { id: "installation", title: "Installation" },  
      { id: "quick-start", title: "Quick Start" },
      { id: "configuration", title: "Configuration" }
    ]
  },
  {
    title: "Integration Guides", 
    items: [
      { id: "react", title: "React Integration" },
      { id: "swift", title: "Swift/macOS" },
      { id: "tauri", title: "Tauri Apps" },
      { id: "electron", title: "Electron Apps" }
    ]
  },
  // Add generated architecture section if available
  ...(docSections.filter(s => s.id === 'architecture').map(section => ({
    title: section.title,
    items: section.docs
  }))),
  {
    title: "Advanced Topics",
    items: [
      { id: "performance", title: "Performance Tuning" },
      { id: "custom-models", title: "Custom Models" },
      { id: "security", title: "Security Best Practices" }
    ]
  },
  // Add other generated sections
  ...(docSections.filter(s => s.id !== 'architecture').map(section => ({
    title: section.title,
    items: section.docs
  }))),
  {
    title: "API Reference",
    items: [
      { id: "api-overview", title: "API Overview" },
      { id: "methods", title: "Methods" },
      { id: "events", title: "Events" },
      { id: "types", title: "TypeScript Types" }
    ]
  }
];

// Existing section components
function OverviewSection() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-4xl font-bold mb-4">Scout SDK Documentation</h1>
        <p className="text-xl text-gray-600 dark:text-gray-400 mb-8">
          Integrate local-first voice transcription into your applications
        </p>
      </div>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        <Card className="border-gray-200 dark:border-gray-800">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Zap className="w-5 h-5 text-yellow-500" />
              Quick Start
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
              Get up and running with Scout in minutes
            </p>
            <Button variant="outline" size="sm" className="w-full">
              View Guide <ChevronRight className="w-4 h-4 ml-1" />
            </Button>
          </CardContent>
        </Card>

        <Card className="border-gray-200 dark:border-gray-800">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Code className="w-5 h-5 text-blue-500" />
              API Reference
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
              Complete API documentation and examples
            </p>
            <Button variant="outline" size="sm" className="w-full">
              Explore API <ChevronRight className="w-4 h-4 ml-1" />
            </Button>
          </CardContent>
        </Card>

        <Card className="border-gray-200 dark:border-gray-800">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Globe className="w-5 h-5 text-green-500" />
              Examples
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
              Sample projects and integration examples
            </p>
            <Button variant="outline" size="sm" className="w-full">
              Browse Examples <ChevronRight className="w-4 h-4 ml-1" />
            </Button>
          </CardContent>
        </Card>
      </div>

      <div className="bg-blue-50 dark:bg-blue-950/20 rounded-lg p-6 mt-8">
        <div className="flex items-start gap-4">
          <AlertCircle className="w-6 h-6 text-blue-500 flex-shrink-0 mt-1" />
          <div>
            <h3 className="font-semibold mb-2">First Time Using Scout?</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
              We recommend starting with the Quick Start guide to understand the basic concepts 
              and get a simple integration working. Then explore the API reference for more 
              advanced usage.
            </p>
            <div className="flex gap-3">
              <Button size="sm">
                Quick Start Guide <ChevronRight className="w-4 h-4 ml-1" />
              </Button>
              <Button variant="outline" size="sm">
                View Examples
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// Component to render generated documentation
function GeneratedDocSection({ docId }: { docId: string }) {
  // Find the doc by its ID
  const doc = Object.values(generatedDocs).find((d: any) => d.id === docId);
  
  if (!doc) {
    return (
      <div className="space-y-6">
        <div className="bg-yellow-50 dark:bg-yellow-950/20 rounded-lg p-6">
          <div className="flex items-start gap-4">
            <AlertCircle className="w-6 h-6 text-yellow-500 flex-shrink-0 mt-1" />
            <div>
              <h3 className="font-semibold mb-2">Documentation Not Built</h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                This documentation hasn't been generated yet. Run <code className="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded">pnpm build:docs</code> to generate it from the markdown files.
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }
  
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-4xl font-bold mb-4">{(doc as any).title}</h1>
      </div>
      <DocsContent content={(doc as any).content} />
    </div>
  );
}

// Placeholder sections (will be replaced with generated docs where available)
function InstallationSection() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-4xl font-bold mb-4">Installation</h1>
        <p className="text-xl text-gray-600 dark:text-gray-400 mb-8">
          Install Scout SDK in your project
        </p>
      </div>

      <div className="space-y-8">
        <section>
          <h2 className="text-2xl font-semibold mb-4">Package Managers</h2>
          
          <div className="space-y-4">
            <div>
              <h3 className="text-lg font-medium mb-2">npm</h3>
              <PrismCode 
                code="npm install @scout-voice/sdk" 
                language="bash"
              />
            </div>

            <div>
              <h3 className="text-lg font-medium mb-2">yarn</h3>
              <PrismCode 
                code="yarn add @scout-voice/sdk" 
                language="bash"
              />
            </div>

            <div>
              <h3 className="text-lg font-medium mb-2">pnpm</h3>
              <PrismCode 
                code="pnpm add @scout-voice/sdk" 
                language="bash"
              />
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">Requirements</h2>
          <ul className="list-disc list-inside space-y-2 text-gray-600 dark:text-gray-400">
            <li>Node.js 16 or later</li>
            <li>TypeScript 4.5 or later (for TypeScript projects)</li>
            <li>Modern browser with Web Audio API support</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">Platform Support</h2>
          <div className="grid gap-4 md:grid-cols-2">
            <Card className="border-gray-200 dark:border-gray-800">
              <CardHeader>
                <CardTitle className="text-lg">Desktop</CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-green-500" />
                    <span>macOS (Apple Silicon & Intel)</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-green-500" />
                    <span>Windows 10/11</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-green-500" />
                    <span>Linux (Ubuntu, Debian, Fedora)</span>
                  </li>
                </ul>
              </CardContent>
            </Card>

            <Card className="border-gray-200 dark:border-gray-800">
              <CardHeader>
                <CardTitle className="text-lg">Mobile</CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-green-500" />
                    <span>iOS 14+ (via Swift SDK)</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 text-yellow-500" />
                    <span>Android (Coming Soon)</span>
                  </li>
                </ul>
              </CardContent>
            </Card>
          </div>
        </section>
      </div>
    </div>
  )
}

// Map of section IDs to components
const sectionComponents: Record<string, React.ComponentType> = {
  overview: OverviewSection,
  installation: InstallationSection,
  // Add more placeholder sections as needed
};

export default function DocsPageContent() {
  const [selectedSection, setSelectedSection] = useState("overview")

  // Check if this is a generated doc
  const isGeneratedDoc = Object.values(generatedDocs).some((doc: any) => doc.id === selectedSection);
  
  // Get the component for the selected section
  const SectionComponent = isGeneratedDoc 
    ? () => <GeneratedDocSection docId={selectedSection} />
    : sectionComponents[selectedSection] || (() => (
        <div className="text-center py-12">
          <p className="text-gray-500">Documentation section not found</p>
        </div>
      ));

  return (
    <>
      <SDKNav />
      
      <div className="container mx-auto px-4 py-8">
        <div className="flex gap-8">
          {/* Sidebar Navigation */}
          <aside className="w-64 flex-shrink-0 hidden lg:block">
            <div className="sticky top-20 space-y-6">
              {navSections.map((section, idx) => (
                <div key={idx}>
                  <h3 className="font-semibold text-sm uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-2">
                    {section.title}
                  </h3>
                  <ul className="space-y-1">
                    {section.items.map((item: any) => (
                      <li key={item.id}>
                        <button
                          onClick={() => setSelectedSection(item.id)}
                          className={`w-full text-left px-3 py-2 rounded-md text-sm transition-colors ${
                            selectedSection === item.id
                              ? 'bg-blue-50 dark:bg-blue-950/30 text-blue-600 dark:text-blue-400 font-medium'
                              : 'hover:bg-gray-100 dark:hover:bg-gray-800 text-gray-700 dark:text-gray-300'
                          }`}
                        >
                          {item.title}
                        </button>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </aside>

          {/* Main Content */}
          <main className="flex-1 max-w-4xl">
            <SectionComponent />
          </main>
        </div>
      </div>
    </>
  )
}